### ISSUE TITLE
로그인 전, 로그인 후에 관한 이슈

### ISSUE THREAD

**Issue by cnpcnp99** [shinwonse/BULS_OWN-SHOP#16]
로그인 전, 로그인 후에 웹페이지 변화가 필요

1. 로그인 전일 경우, Sigin-Up, Sigin-In 버튼만 보여야 함
2. 로그인 후일 경우, My Page, Log out 버튼만 보여야 함
3. 관리자 아이디를 따로 만들고 나면, 관리자 아이디로 로그인 시, Administrator, Log out 버튼만 보여야 함

**Comment by shinwonse** [comment]
그래서 이것도 얘기하려했었는데 일단은 그렇게만 만들어둔거임 이 부분은 html 수정하면 되지 않을까싶음
main 페이지를 두가지 경우로 만들어야하나

**Comment by cnpcnp99** [comment]
이 부분의 경우 WEB에서 Session 혹은 Cookie에 대한 이해가 선행돼야 하고(우리의 경우 Session이 적합다고 생각)
웹페이지 변화같은 경우 자바 스크립트로 구현 가능한 듯

참고 페이지 https://taes-k.github.io/2019/06/12/spring-security-1/

**Comment by cnpcnp99** [comment]
관리자 아아디 : root
관리자 비번     : 1234
